server:
  port: 8080

spring:
  application:
    name: reserva
  profiles:
    active: local
  jpa:
    open-in-view: false
  hibernate:
    format_sql: true
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG